description: spacy_ner_const
hyperparameters:
  global_batch_size: 1
  dropout: 0.5
  lr: 0.01
  beta1: 0.9
  beta2: 0.99
searcher:
  name: single
  metric: val_f1
  smaller_is_better: false
  max_length:
    batches: 50
entrypoint: model_def:SpacyNerTrial
min_validation_period:
  batches: 5
